### ISSUE TITLE
Does avx_xorshift128plus() generate same sequence as original xorshift128plus.c?

### ISSUE THREAD

**Issue by t-mat** [lemire/SIMDxorshift#9]
Hi @lemire, thank you for the useful code!

I have a naive question about `avx_xorshift128plus()`.  Does it generate same sequence as original xorshift128plus.c?

I supposed when I gave same `key1` and `key2` to `xorshift128plus_init()` and `avx_xorshift128plus_init()`, `xorshift128plus()` and lowest 64 bit lane of `avx_xorshift128plus()` generates same sequence.

I've tried the following code

```C
#include <stdio.h>
#include <inttypes.h>
#include "simdxorshift128plus.h"
#include "xorshift128plus.h"

int main() {
    const uint64_t key1 = 324;
    const uint64_t key2 = 4444;
    {
        printf("xorshift128plus()\n");
        xorshift128plus_key_t key;
        xorshift128plus_init(key1, key2, &key);
        for(int i = 0; i < 4; ++i) {
            const uint64_t v = xorshift128plus(&key);
            printf("i=%d, %016" PRIx64 "\n", i, v);
        }
    }
    {
        printf("avx_xorshift128plus()\n");
        avx_xorshift128plus_key_t key;
        avx_xorshift128plus_init(key1, key2, &key);
        for(int i = 0; i < 4; ++i) {
            const __m256i v = avx_xorshift128plus(&key);
            union U {
                __m256i u256;
                uint64_t u64[4];
            } u;
            u.u256 = v;
            printf("i=%d, ", i);
            printf("%016" PRIx64 ", ", u.u64[0]);
            printf("%016" PRIx64 ", ", u.u64[1]);
            printf("%016" PRIx64 ", ", u.u64[2]);
            printf("%016" PRIx64 "\n", u.u64[3]);
        }
    }
    return 0;
}
```

But above code outputs the following sequences:

```
xorshift128plus()
i=0, 00000000a200496e
i=1, 00000008ab123b20
i=2, 00510008ab6f84d2
i=3, 04a80008ad7c8f04

avx_xorshift128plus()
i=0, 00000008ae023c66, 3869ed045ddae7e2, 6b826340a2f2b209, 85f43fbcf04fb5f8
i=1, 04570008ae3986a2, 88ec543d470b3c74, 9f18502273d1ffd7, e29ddbac3683852a
i=2, 0479a2b80b222569, 1ec3fe354c920644, 10e17fd02388f80d, dd1e114ed0ef2edc
i=3, 5c271a30e80b38a5, 17f21edf8a60db14, e653258226804f7e, a9a53a8a8735680d
```

I've checked `avx_xorshift128plus()`.

https://github.com/lemire/SIMDxorshift/blob/04064ed9c6c41b844e2988472518c78a51a9bb24/src/simdxorshift128plus.c#L49-L58

I think [line #53](https://github.com/lemire/SIMDxorshift/blob/04064ed9c6c41b844e2988472518c78a51a9bb24/src/simdxorshift128plus.c#L53) makes difference.

When I replace this line with the following patch,

```C
-	s1 = _mm256_xor_si256(key->part2, _mm256_slli_epi64(key->part2, 23));
+	s1 = _mm256_xor_si256(s1, _mm256_slli_epi64(s1, 23));
```

it generates the following sequence which matches original `xorshift128plus()`.

```
avx_xorshift128plus()
i=0, 00000000a200496e, 1e0ecd55a5429b74, 9c9b64fc8ff5e750, 36c5602a44649eda
i=1, 00000008ab123b20, c97ee0e41d03b58b, cdc45acd51153a37, e84499a5edefc404
i=2, 00510008ab6f84d2, 79d2b441a896dbcd, b2fbc4c20cfe92e0, c87f6e0cd13b8045
i=3, 04a80008ad7c8f04, 6b5a1f5ddf11088e, 7f5591e4c866a113, b6067b6a4c632679
```

My questions are:

- (Q.1) Is this intentional change?

- (Q.2) Does output of `avx_xorshift128plus()` have same quality of randomness as original `xorshift128plus.c`?

**Comment by lemire** [comment]
> Does it generate same sequence as original xorshift128plus.c?

I would not expect so. Instead, it should provide multiple streams of the xorshift128 generator.

>  Is this intentional change?

Yes in the sense that it was never meant to generate the same output as the scalar version. When you vectorized, you need to have independent streams if you are going to have good performance.

>  Does output of avx_xorshift128plus() have same quality of randomness as original xorshift128plus.c?

That is my expectation.
